### ISSUE TITLE
bug: Links from layout page to Keymanweb always reverts to Askhara Bali unicode layout

### ISSUE THREAD

**Issue by sapradhan** [keymanapp/keymanweb.com#17]
**Describe the bug**
Links to use Keyboard Online on keyboard layout pages do not work 

**To Reproduce**

1. Go to *any* keyboard page eg [Newa Traditional](https://keyman.com/keyboards/newa_traditional)
2. Click on Use keyboard Online
3. Instead of Newa Traditional (or whichever keyboard) being selected, Akshara Bali is selected, Url fragment changes to `#ban-bali,Keyboard_aksarabali_panlex` 
5. Same behavior is observed if you enter the url https://keymanweb.com/#new-newa,Keyboard_newa_traditional manually.
6. Same behavior on few random layouts that I selected.

**Expected behavior**
Selected keyboard should be retained.

---

**KeymanWeb:**
 - OS: Windows 10, Archlinux
 - Browser: Chrome 87, Firefox 84
 - KeymanWeb Version: latest ?
 - URL: https://keymanweb.com/#new-newa,Keyboard_newa_traditional

---

**Keyboard**
 - Keyboard name: Any
 - Keyboard version: Any
 - Language name: Any

**Additional context**
This was working until very recently. It may not be related at all -- but https://github.com/keymanapp/r.keymanweb.com/pull/6 was merged yesterday to make bookmarklet to work.

When language is selected manually, there is [undefined] seen next to layout name
![image](https://user-images.githubusercontent.com/5070211/105166586-b30d6980-5b3f-11eb-965e-4d4ca150bfd7.png)

**Comment by mcdurdin** [comment]
@sapradhan thank you for reporting this. I am investigating!

**Comment by mcdurdin** [comment]
Regression introduced in #15.

**Comment by mcdurdin** [comment]
I have tried rolling back the change from #15, along with some other changes. The issue arises because we are adding keyboards before keymanweb is initialised, but that does not resolve the problem. The primary issue is a conflict between which component is responsible for selecting the active keyboard.

In kmwkeyboards.ts:mergeStub() (line 324, v13.0), we automatically activate the first keyboard in the list, which cascades to a failure if KeymanWeb is not initialised. There are a few things we should do:

1. Have a method of registering keyboards without activating under any circumstances (separate those concerns)
2. Ensure registration does not attempt to activate the keyboard before initialisation
3. Fix the kmwutils.ts::alert() function to avoid throwing if the `bg` element does not exist.
4. On keymanweb.com, we register the preferred keyboard with a minimal stub before registering all other keyboards. This stops the first keyboard on the list being loaded unnecessarily.

See #18, keymanapp/keyman#4304 for fixes. #18 resolves the immediate issue, and the other one improves performance and reliability.
